// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelManagementSystem.Data;

#nullable disable

namespace ParcelManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250803100639_parcel")]
    partial class Parcel 
    {
    }
}
